BCCBUDDY_DB = {ADDON_NAME = "BCCBuddy", ["test"] = 1}
BCCBUDDY_CHARACTER_DB = {["QUESTS_COMPLETED"] = {}}
SLOTS = {
    "HeadSlot", "NeckSlot", "ShoulderSlot", "BackSlot", "ChestSlot",
    "ShirtSlot", "TabardSlot", "WristSlot", "HandsSlot", "WaistSlot",
    "LegsSlot", "FeetSlot", "Finger0Slot", "Finger1Slot", "Trinket0Slot",
    "Trinket1Slot", "MainHandSlot", "SecondaryHandSlot"
}
-- stat ids
STAT_ID_STRENGTH = 1
STAT_ID_AGILITY = 2
STAT_ID_STAMINA = 3
STAT_ID_INTELLECT = 4
STAT_ID_SPIRIT = 5
-- spell tree globals
SPELL_TREE_ID_PHYSICAL = 1
SPELL_TREE_ID_HOLY = 2
SPELL_TREE_ID_FIRE = 3
SPELL_TREE_ID_NATURE = 4
SPELL_TREE_ID_FROST = 5
SPELL_TREE_ID_SHADOW = 6
SPELL_TREE_ID_ARCANE = 7
-- combat rating globals
CR_UNUSED_1 = 1;
CR_DEFENSE_SKILL = 2;
CR_DODGE = 3;
CR_PARRY = 4;
CR_BLOCK = 5;
CR_HIT_MELEE = 6;
CR_HIT_RANGED = 7;
CR_HIT_SPELL = 8;
CR_CRIT_MELEE = 9;
CR_CRIT_RANGED = 10;
CR_CRIT_SPELL = 11;
CR_CORRUPTION = 12;
CR_CORRUPTION_RESISTANCE = 13;
CR_SPEED = 14;
COMBAT_RATING_RESILIENCE_CRIT_TAKEN = 15;
COMBAT_RATING_RESILIENCE_PLAYER_DAMAGE_TAKEN = 16;
CR_LIFESTEAL = 17;
CR_HASTE_MELEE = 18;
CR_HASTE_RANGED = 19;
CR_HASTE_SPELL = 20;
CR_AVOIDANCE = 21;
CR_UNUSED_2 = 22;
CR_WEAPON_SKILL_RANGED = 23;
CR_EXPERTISE = 24;
CR_ARMOR_PENETRATION = 25;
CR_MASTERY = 26;
CR_UNUSED_3 = 27;
CR_UNUSED_4 = 28;
CR_VERSATILITY_DAMAGE_DONE = 29;
CR_VERSATILITY_DAMAGE_TAKEN = 31;
COMBAT_RATINGS = {
    [1] = "CR_UNUSED_1",
    [2] = "CR_DEFENSE_SKILL",
    [3] = "CR_DODGE",
    [4] = "CR_PARRY",
    [5] = "CR_BLOCK",
    [6] = "CR_HIT_MELEE",
    [7] = "CR_HIT_RANGED",
    [8] = "CR_HIT_SPELL",
    [9] = "CR_CRIT_MELEE",
    [10] = "CR_CRIT_RANGED",
    [11] = "CR_CRIT_SPELL",
    [12] = "CR_CORRUPTION",
    [13] = "CR_CORRUPTION_RESISTANCE",
    [14] = "CR_SPEED",
    [15] = "COMBAT_RATING_RESILIENCE_CRIT_TAKEN",
    [16] = "COMBAT_RATING_RESILIENCE_PLAYER_DAMAGE_TAKEN",
    [17] = "CR_LIFESTEAL",
    [18] = "CR_HASTE_MELEE",
    [19] = "CR_HASTE_RANGED",
    [20] = "CR_HASTE_SPELL",
    [21] = "CR_AVOIDANCE",
    [22] = "CR_UNUSED_2",
    [23] = "CR_WEAPON_SKILL_RANGED",
    [24] = "CR_EXPERTISE",
    [25] = "CR_ARMOR_PENETRATION",
    [26] = "CR_MASTERY",
    [27] = "CR_UNUSED_3",
    [28] = "CR_UNUSED_4",
    [29] = "CR_VERSATILITY_DAMAGE_DONE",
    [30] = "CR_VERSATILITY_DAMAGE_TAKEN"
}